<a href="https://colab.research.google.com/github/MatthewK321/Python_Pandas-Projects-Repo/blob/main/Python_Day_3_(Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/student.xlsx")

Inspecting Dataframe

In [ ]:
# Returnes first five rows
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
# Returns last 5 rows
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.tail(3)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
33  34    Gain Toe  Seven    69    male
34  35  Rows Noump    Six    88  female

In [ ]:
# Returns random sample of data
df.sample()

    id  name  class  mark  gender
13  14  Bigy  Seven    88  female

In [ ]:
df.sample(3)

    id         name  class  mark  gender
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
0    1     John Deo   Four    75  female

In [ ]:
# Shows you how many rows and columns the dataset has (Attribute)
df.shape

(35, 5)

In [ ]:
# Returns important information in dataset  # Object means string
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
# Shows you the columns in your dataset
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
# Shows statistical summary of dataset
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
len(df)

35

In [ ]:
# Shows rows * Columns
df.size

175

In [ ]:
# Returns data types of the columns
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
# Counts missing values within columns, can be include with or without .sum
df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
# counts duplicated rows
df.duplicated().sum()

np.int64(0)

Sub-Setting a Dataframe

In [ ]:
df["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
Name: id, dtype: int64

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df["gender"].head()

0    female
1      male
2      male
3    female
4    female
Name: gender, dtype: object

In [ ]:
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
# Use slicing brackets to find multiple columns in dataset, one set of brackets represnting list item other being column names
df[["name", "class"]]

           name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
5     Alex John   Four
6   My John Rob  Fifth
7        Asruid   Five
8       Tes Qry    Six
9      Big John   Four
10       Ronald    Six
11        Recky    Six
12          Kty  Seven
13         Bigy  Seven
14     Tade Row    NaN
15        Gimmy   Four
16        Tumyu    Six
17        Honny   Five
18        Tinny   Nine
19       Jackly   Nine
20   Babby John   Four
21       Reggid  Seven
22        Herod  Eight
23    Tiddy Now  Seven
24     Giff Tow  Seven
25       Crelea  Seven
26          NaN  Three
27    Rojj Base  Seven
28  Tess Played  Seven
29    Reppy Red    Six
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

In [ ]:
df[["id","name","gender"]].sample()

    id  name  gender
13  14  Bigy  female

In [ ]:
df.groupby('gender')['mark'].mean()

gender
female    77.312500
male      71.588235
Name: mark, dtype: float64

Loc and Iloc for subsetting data
# df.loc[row,index(es), column name(s)]
# df.iloc[row index(es), column index(es)]
# Indexes in Python starts from zero. First column is Index 0

In [ ]:
df.loc[3, "name"]

'Krish Star'

In [ ]:
df.loc[25, "mark"]

np.int64(79)

In [ ]:
df.iloc[3, 1]

'Krish Star'

In [ ]:
df.iloc[25, 3]

np.int64(79)

In [ ]:
df.loc[3, ["name", "gender"]]

name      Krish Star
gender        female
Name: 3, dtype: object

In [ ]:
df.iloc[3,[1,4]]

name      Krish Star
gender        female
Name: 3, dtype: object

In [ ]:
df.loc[[5,15,25], ["name", "class"]]

         name  class
5   Alex John   Four
15      Gimmy   Four
25     Crelea  Seven

In [ ]:
df.iloc[[5,15,25], [1,2]]

In [ ]:
# 1:4 represents the range of rows
df.loc[1:4, ["name", "mark"]]

         name  mark
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60
4   John Mike    60

Filtering dataframe (loc and Iloc)

In [ ]:
# Returns students with marks greater than 90
df[df["mark"] > 90]

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

In [ ]:
df[df["class"]=="Seven"]

    id         name  class  mark  gender
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
21  22       Reggid  Seven    55  female
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
31  32    Binn Rott  Seven    90  female
33  34     Gain Toe  Seven    69    male

In [ ]:
df[(df["gender"]=="male") & (df["class"]=="four")]

Empty DataFrame
Columns: [id, name, class, mark, gender]
Index: []

In [ ]:
df[(df["mark"]<90) & (df["gender"]=="female")]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
34  35  Rows Noump    Six    88  female

In [ ]:
# average mark of the female student
df[df["gender"]=="female"]["mark"].mean()

np.float64(77.3125)

In [ ]:
# OR condition uses pipe symbol
df[(df["mark"]<90) | (df["gender"]=="female")]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.loc[df["mark"]>90, :]
# : means all columns

In [ ]:
df.loc[(df["mark"]>80) & (df["class"]=="Five"), ["name", "mark"]]

     name  mark
7  Asruid    85

Using Filter Funtction

In [ ]:
df.filter(items=['name', 'mark'])

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
# Returns column name starting or containing 'ma'
df.filter(like='ma')

    mark
0     75
1     85
2     55
3     60
4     60
5     55
6     78
7     85
8     78
9     55
10    89
11    94
12    88
13    88
14    88
15    88
16    54
17    75
18    18
19    65
20    69
21    55
22    79
23    78
24    88
25    79
26    81
27    86
28    55
29    79
30    88
31    90
32    96
33    69
34    88

In [ ]:
 # Query method filters rows
 # filter method filters columns
 df.query("mark > 60")

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

Sorting Results
# normal sort is ascending
# reverse sort to descending, ascending = false

In [ ]:
# Sorting by names
df.sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="mark", ascending=False)

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male
34  35   Rows Noump    Six    88  female
24  25     Giff Tow  Seven    88    male
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
19  20       Jackly   Nine    65  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [ ]:
df.sort_values(by ="class", ascending=False)

    id         name  class  mark  gender
2    3       Arnold  Three    55    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
34  35   Rows Noump    Six    88  female
8    9      Tes Qry    Six    78     NaN
16  17        Tumyu    Six    54    male
11  12        Recky    Six    94  female
10  11       Ronald    Six    89  female
29  30    Reppy Red    Six    79  female
32  33    Kenn Rein    Six    96  female
28  29  Tess Played  Seven    55    male
27  28    Rojj Base  Seven    86  female
21  22       Reggid  Seven    55  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
15  16        Gimmy   Four    88    male
9   10     Big John   Four    55  female
30  31  Marry Toeey   Four    88    male
5    6    Alex John   Four    55    male
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
7    8       Asruid   Five    85    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
14  15     Tade Row    NaN    88    male

In [ ]:
# return students who are class seven or female
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df.loc[:,:].sort_values(by= ["mark", "class"])

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
22  23        Herod  Eight    79    male
25  26       Crelea  Seven    79    male
29  30    Reppy Red    Six    79  female
26  27          NaN  Three    81     NaN
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
27  28    Rojj Base  Seven    86  female
15  16        Gimmy   Four    88    male
30  31  Marry Toeey   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
24  25     Giff Tow  Seven    88    male
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

Value Counts

In [ ]:
# How many male and female students are there?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64